name: Publish Python package

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
    tags:
      - 'v*'  # Trigger when a new version tag is created (e.g., v0.1.1)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Set the Python version for your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine  # Install the necessary tools

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel  # Build your package

    - name: Upload to PyPI
      run: |
        twine upload dist/*  # Upload the package to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

